-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 16:45:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema concessionaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concessionaria` DEFAULT CHARACTER SET utf8 ;
USE `concessionaria` ;

-- -----------------------------------------------------
-- Table `concessionaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` VARCHAR(11) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `dt_nasc_cliente` DATE NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`funcionario` (
  `id_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `email_funcionario` VARCHAR(100) NULL,
  `telefone_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`modelo` (
  `id_modelo` INT NOT NULL AUTO_INCREMENT,
  `nome_modelo` VARCHAR(45) NULL,
  `cor_modelo` VARCHAR(45) NULL,
  `ano_modelo` YEAR NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`venda` (
  `id_venda` INT NOT NULL,
  `data_venda` DATE NOT NULL,
  `valor_venda` DECIMAL(10,2) NOT NULL,
  `cliente_id_cliente` INT NULL,
  `funcionario_id_funcionario` INT NULL,
  `modelo_id_modelo` INT NULL,
  `vendacol` VARCHAR(45) NULL,
  `cliente_id_cliente1` INT NOT NULL,
  `funcionario_id_funcionario1` INT NOT NULL,
  `modelo_id_modelo1` INT NOT NULL,
  PRIMARY KEY (`id_venda`, `cliente_id_cliente1`, `funcionario_id_funcionario1`, `modelo_id_modelo1`),
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente1` ASC) ,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario1` ASC) ,
  INDEX `fk_venda_modelo1_idx` (`modelo_id_modelo1` ASC) ,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente1`)
    REFERENCES `concessionaria`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario1`)
    REFERENCES `concessionaria`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_modelo1`
    FOREIGN KEY (`modelo_id_modelo1`)
    REFERENCES `concessionaria`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concessionaria`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concessionaria`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nome_marca` VARCHAR(45) NULL,
  `modelo_id_modelo` INT NOT NULL,
  PRIMARY KEY (`id_marca`, `modelo_id_modelo`),
  INDEX `fk_marca_modelo_idx` (`modelo_id_modelo` ASC) ,
  CONSTRAINT `fk_marca_modelo`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `concessionaria`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
